### ISSUE TITLE
Compiled builds

### ISSUE THREAD

**Issue by Keith94** [berkay2578/RockportEd#1]
Hi,
Just wondering are you planning to add compiled builds over on the [releases](https://github.com/berkay2578/RockportEd/releases) page, and any release date for that? Thanks!

**Comment by berkay2578** [comment]
The current code in the repo is laughingly bad, I'm currently rewriting it and adding new features on the way. Like a [TimeOfDayLighting editor.](https://i.imgur.com/VZ8hT67.png) After I'm done rewriting the code, I'll upload a compiled build.

**Comment by Keith94** [comment]
Sounds good, waiting to try it out.

**Comment by berkay2578** [comment]
Added.

**Comment by Keith94** [comment]
Thanks dude :-)

**Comment by Keremakgullu** [comment]
Gün saatini değiştirebildiğimiz versiyonu her yerden silinmiş, rica etsem paylaşabilir misin ustam?
