### ISSUE TITLE
Save settings between sessions

### ISSUE THREAD

**Issue by Keith94** [berkay2578/RockportEd#2]
Hello, I did a quick test of [RockportEd v0.9](https://nfsmods.xyz/mod/270) with the game. The camera editor has some very useful features. :) I saw the option to save the preset, but on next launch of the game it still uses default values (FOV, etc). Are you adding the ability to load (automatically or manually) our settings?

**Comment by berkay2578** [comment]
Yes, it's a known bug. You have to enable the Camera Editor and switch
between the cameras while it's enabled and it will load the data.

**Comment by Keith94** [comment]
Ah, I see. I had another question for the camera settings but I'll wait for a future build.

**Comment by berkay2578** [comment]
You can post it as a seperate issue, anything can be put up here as long as it's related to the project.

**Comment by berkay2578** [comment]
Fixed.
